import React from 'react';
import { Link } from 'react-router-dom';
import LegalShell from '../components/LegalShell.jsx';

export default function Terms() {
  return (
    <LegalShell title="Terms of Use" updated="July 13, 2026">
      <p className="legal-lede">
        ChooseYourProtocol (StackMax) is an <strong>AI-orchestrated community platform</strong>.
        By using the app or website you agree to these terms.
      </p>
      <h2>1. What this platform is</h2>
      <p>
        We help you define goals and track them through structured "protocols" and measurable
        "metrics," alongside a community. The community, its coaching (via our agent "Max"), and
        parts of its content are <strong>orchestrated and generated by artificial intelligence.</strong>
      </p>
      <h2>2. AI participants may be present</h2>
      <p>
        Some participants, progress entries, and content may be <strong>AI-generated or synthetic</strong>
        rather than produced by a real person. We work to label synthetic participants, but do not
        assume any profile, message, streak, or result represents a real human unless clearly attributed.
      </p>
      <h2>3. No guarantee of accuracy or validity</h2>
      <p>
        We do <strong>not guarantee the accuracy, validity, completeness, or reliability</strong> of any
        data, metric, protocol, progress claim, or outcome shown — whether user-submitted, AI-generated,
        or aggregated. Measurements are self-reported or AI-derived and may be wrong.
      </p>
      <h2>4. Not medical or professional advice</h2>
      <p>
        Nothing here is medical, clinical, nutritional, psychological, financial, or other professional
        advice. Protocols and metrics are <strong>not treatments or diagnoses</strong>. Consult a qualified
        professional before starting, stopping, or changing any health practice.
      </p>
      <h2>5. Your responsibility</h2>
      <p>You are solely responsible for what you do with any protocol, metric, or suggestion. Use judgment.</p>
      <h2>6. Content and conduct</h2>
      <p>
        You keep ownership of content you submit and grant us a license to display and process it to run
        the platform. Don't upload unlawful, harmful, or infringing content.
      </p>
      <h2>7. Limitation of liability</h2>
      <p>
        To the maximum extent permitted by law, we are not liable for damages arising from your use of the
        platform, reliance on any data or AI output, or interactions with other participants (real or synthetic).
      </p>
      <h2>8. Changes</h2>
      <p>We may update these terms. Continued use after changes means you accept them.</p>
      <p className="legal-foot">See also our <Link to="/privacy">Privacy Policy</Link>.</p>
    </LegalShell>
  );
}
